### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by NicolasGorga** [luluhoc/medusa-plugin-sendgrid-typescript#21]
Hey, sorry posting this as an issue as i have no other way of contacting you currently hehe (if you are willing to share your details would be more than happy to connect :) ). Could you publish a new version to npm with the changes you just merged, so i can start using it right away? Thanks!

**Comment by luluhoc** [comment]
@NicolasGorga I created github actions to publish, but there is some issue with your pull it through type errors

https://github.com/luluhoc/medusa-plugin-sendgrid-typescript/actions/runs/11710815001

**Comment by NicolasGorga** [comment]
Yes i saw, fixing now, they are just some typescript errors

**Comment by luluhoc** [comment]
I fixed it. @NicolasGorga

**Comment by NicolasGorga** [comment]
Saw that too, thanks man!

**Comment by luluhoc** [comment]
It's up https://www.npmjs.com/package/medusa-plugin-sendgrid-typescript
