### ISSUE TITLE
sendNotification event parameter has wrong typing.

### ISSUE THREAD

**Issue by NicolasGorga** [luluhoc/medusa-plugin-sendgrid-typescript#3]
https://github.com/luluhoc/medusa-plugin-sendgrid-typescript/blob/1605244a1c50f54f157d3c9b46d10a53213d655b/src/services/sendgrid.ts#L236

The type for the parameter 'eventData' of the functionin question is wrong. The type of this variable could potentially be anything at runtime, specially for custom events that are defined by the consumers of the plugin. Why is this typed like this?

I would have understanded if you typed it with the properties that should be defined, since they are needed inside the body of the sendNotification function, plus an intersection type with Record<string, unknown>, to be representative of the dynamic nature of the variable.

Based on the properties used in the function, i would type the parameter as:

`interface SendNotificationEventData = {
locale?: string,
email: string,
order?: Order,
return_request?: {
items?: LineItem[]
}
} & Record<string, unknown>`

This is just a quick analysis based on the properties i see used. 

A more simplified version would be to just specify the email property as required string and intersecting with Record<string, unknown>.

What do you think, could open a PR!

**Comment by luluhoc** [comment]
@NicolasGorga You can create a PR, thanks

**Comment by NicolasGorga** [comment]
Pull request created! https://github.com/luluhoc/medusa-plugin-sendgrid-typescript/pull/10
